#!/usr/bin/env ruby
# Exit with specific code after random delay
# Usage: exit-code [code]
# If no code given, picks random 1-10

code  = ARGV[0]&.to_i || rand(1..10)
delay = rand * 0.2

$stdout.sync = true
puts "exiting with code #{code} after #{(delay * 1000).round}ms"
sleep delay
exit code
