#!/usr/bin/env ruby
# Defective process: crashes randomly
$stdout.sync = true
loop do
  puts "tick"
  sleep 0.05
  next unless rand < 0.3

  case rand(3)
  when 0 then raise "random error!"
  when 1 then exit 42
  when 2 then Process.kill("SEGV", $$)
  end
end
