#!/usr/bin/env ruby
# Defective process: crashes randomly
$stdout.sync = true
loop do
  puts "tick"
  sleep 0.05
  if rand < 0.3
    case rand(3)
    when 0
      raise "random error!"
    when 1
      exit 42
    when 2
      Process.kill("SEGV", $$)
    end
  end
end
